# Generated by Django 3.2.19 on 2023-06-21 13:53

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='volunteer_profiles',
            fields=[
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=20)),
                ('phone_number', models.IntegerField(default=0)),
                ('ngo_association', models.CharField(max_length=100)),
                ('area_of_operation', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Volunteer Profile',
            },
        ),
    ]
