# Generated by Django 4.2.1 on 2023-06-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer_profiles',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
