# Generated by Django 4.2.1 on 2023-06-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_volunteer_profiles_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer_profiles',
            name='id',
        ),
        migrations.AlterField(
            model_name='volunteer_profiles',
            name='volunteer_no',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
