# Generated by Django 4.2.1 on 2023-06-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_remove_volunteer_profiles_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer_profiles',
            name='volunteer_no',
        ),
        migrations.AddField(
            model_name='volunteer_profiles',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
