# Generated by Django 4.2.1 on 2023-06-19 15:32

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_profiles',
            fields=[
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('home_name', models.CharField(max_length=50)),
                ('home_address', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField(default=0)),
                ('contact_person', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('CORPORATION', 'CORPORATION'), ('PRIVATE', 'PRIVATE'), ('OTHER', 'OTHER')], max_length=20)),
                ('beds', models.IntegerField(max_length=5)),
            ],
            options={
                'verbose_name': 'HOMES',
            },
        ),
        migrations.DeleteModel(
            name='volunteer_profiles',
        ),
    ]
