# Generated by Django 3.2.19 on 2023-06-21 13:53

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_profiles',
            fields=[
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('memo_no', models.IntegerField(blank=True, default='')),
                ('first_name', models.CharField(blank=True, default='', max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=50)),
                ('age', models.IntegerField(blank=True, default='')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=20)),
                ('ngo_assigned', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('pickup_location', models.CharField(max_length=1000)),
                ('pickup_date', models.DateTimeField()),
                ('Image', models.ImageField(default='', upload_to='victims/images')),
            ],
            options={
                'verbose_name': 'All Profile',
            },
        ),
    ]
