# Generated by Django 3.2.19 on 2023-05-11 17:07

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('Volunteer_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=11, max_length=11, prefix='', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=20)),
                ('associated_ngo', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('operating_location', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'All Volunteers',
            },
        ),
    ]
