# Generated by Django 3.2.19 on 2023-05-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victims', '0002_auto_20230511_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_profiles',
            name='Image',
            field=models.ImageField(default='', upload_to='victims/images'),
        ),
    ]
