# Generated by Django 3.2.19 on 2023-05-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victims', '0003_alter_all_profiles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_profiles',
            name='Image',
            field=models.ImageField(default='', upload_to='human_profile/images'),
        ),
    ]
