# Generated by Django 4.2.1 on 2023-05-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victims', '0004_alter_all_profiles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_profiles',
            name='Image',
            field=models.ImageField(default='', upload_to='victims/images'),
        ),
    ]
