# Generated by Django 4.2.1 on 2023-06-19 19:31

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('victims', '0010_alter_all_profiles_id_alter_all_profiles_memo_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_profiles',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='all_profiles',
            name='memo_no',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
