# Generated by Django 4.2.1 on 2023-06-21 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('victims', '0011_alter_all_profiles_id_alter_all_profiles_memo_no'),
        ('victims', '0013_alter_all_profiles_id'),
    ]

    operations = [
    ]
